### ISSUE TITLE
About material UV error

### ISSUE THREAD

**Issue by rtjia** [Fransferdy/creaturecreator#4]
1. In my test case, i read  mesh data

**Comment by Fransferdy** [comment]
Bones have nothing to do with the material.

From my understanding, FRuntimeSkeletalMeshGenerator will receive an array of surfaces and an array of materials, each Surface will receive the material corresponding to the same array index of the materials array. So for each material in your mesh, you have to construct a surface separately and match the indexes of those surfaces in the array you pass to the function with the indexes of the material array.
If you are doing that correctly, then I would guess that the part of your code assigning the UVs to each vertex might have a bug, or the plugin might have a bug.

 I would like to take a look at your code, is that possible ? How are you loading the material?

**Comment by rtjia** [comment]
it works well on UE5 , in my test case , for StaticMesh and procdualMesh works fine. I noticed that the relationship between surface and material is one-to-one, and I also tried to match them. but ,in SkeletalMesh , have some error.

The demo project too large, i will send UE_Assimp folder in next link.

**Comment by rtjia** [comment]
the source folder location in "UEDemos\AssimpSkeletalMesh\Plugins\UE4_Assimp\",and have a ThridParty folder, too large, you can get it form "https://github.com/irajsb/UE4_Assimp".

Thanks again.

**Comment by Fransferdy** [comment]
Okay, I got your sample to build here, first thing, during bone generation, you'll have to set the parents of each bone to the correct father bone(the function you copied from my project assigns every bone as children of the root)
here: const FMeshBoneInfo boneInfo(boneName, boneNameExt, 0); the third parameter is the index of the father bone.
also, I think you don't need this for:
for (int32 bone = rootBoneIndex - 1; bone >= 0; bone--)
{
	FName boneName(bonesData[bone]->name + "in");
	FString boneNameExt(bonesData[bone]->name + "ext");
	const FMeshBoneInfo boneInfo(boneName, boneNameExt, 0);
	//FTransform boneTransform((bonesData[bone]->transform.GetLocation() - bonesData[rootBoneIndex]->transform.GetLocation()));
	FTransform boneTransform((bonesData[bone]->transform));

	RefSkelModifier.Add(boneInfo, boneTransform);
	UE_LOG(LogTemp, Warning, TEXT("OtherBoneFront: %s"), *boneNameExt);
}

In my logic, I was generating bones from the middle of a worm, to the extremities, that's why there is a for going up and another going down.

Regarding the UVs, seems there really is a bug with the plugin, but there are some people looking into it.

**Comment by Fransferdy** [comment]
Okay, so I managed to backport this to UE 5.1 which "supposedly is working", and got the following results:
![Comparison](https://github.com/user-attachments/assets/fa385492-0d51-4fc5-9235-8bc0dbf0940c)

So not much different from UE 5.4(just different shading). Now we can come to two conclusions, UVs never worked correctly in this plugin or there might be either: a bug in your code when setting the UVs to the surfaces, a "incompatibility" between the way you are putting the UVs to the surfaces, in relation to this plugin, or yet another bug in the plugin(It wouldn't be the first).

If I were you, I would try to load a simpler mesh( such as a cube ) using 2-3-4 materials, or a different material for each face, an check how the UVs fare there, use a texture for each face, and different UVs for each quarter of a face. Basically create a UV testing cube a try to load it.

**Comment by rtjia** [comment]
Thank you for your help, I will continue to look for this error according to your advice, keep in touch, thanks again

**Comment by Fransferdy** [comment]
Man, another ccontributor commented about thiss project:
https://github.com/rdeioris/glTFRuntime?tab=readme-ov-file
I recommend you take a look.

**Comment by rtjia** [comment]
WOW, Let me see... Maybe

**Comment by rtjia** [comment]
I have a question. I read the introduction of glTF and it seems that I can specify Skeletal/Bone for UStaticMesh/USkeletalMesh at runtime? If so, I don't need to deal with MeshSurface, but only need to process UStaticMesh and create Bones at runtime, right? Or do I need to implement a glTFRuntimeAC3D first, and then use the basic functions to achieve the above goals?

**Comment by Fransferdy** [comment]
Since you want the skeleton binding all those meshes together as one, I think you would have to write your own importer, but following whatever it is they are doing to import gltf.

If you didn't had that requirement, you could just convert .ac to .gltf and import it that way.
But that is not the only thing you are doing right ?

**Comment by rtjia** [comment]
Yes
